"use strict";

/* ---------- ТУРЕЦКИЙ ---------- */
registerLang("tr", { name:"TÜR" }, {
  pageTitle:"DieFliegendeKuh · Unregelmäßige Verben 1–270 · Antrenör, Sözlük ve Kartlar",
  pageTitle_prep:"DieFliegendeKuh · Verben mit Präpositionen · Antrenör, Sözlük ve Kartlar",
  subtitle:"Unregelmäßige Verben",
  subtitle_prep:"Verben mit Präpositionen",
  courseVerbs:"🔤 Fiil çekimleri", coursePrep:"🔗 Fiiller + edatlar",
  navHome:"🎯 Antrenör", navDict:"📖 Sözlük", navLearn:"🗂️ Kartlar",
  rangeTitle:"📍 Fiil aralığı",
  lblFrom:"başlangıç", lblTo:"bitiş",
  lblLearned:"📗 Öğrenildi", lblNotLearned:"📕 Öğrenilmedi", lblNew:"📘 Yeni", lblRepeated:"🟡 Tekrar edildi",
  whatTrainTitle:"🎯 Ne çalışılacak", whatTrainSub:"seçili aralıkta",
  chkShuffleLbl:"Karıştır", chkTransLbl:"Çeviriyi sor", chkPerfLbl:"Perfekt'i sor",
  chkPerfLbl_prep:"Edatı sor",
  ansModeTitle:"✍️ Nasıl cevaplanacak", ansModeSub:"çeviri ve Perfekt alanı için", ansModeSub_prep:"çeviri ve «edat + hâl» alanı için",
  ansModeInput:"⌨️ Cevabı yaz", ansModeChoice:"🔘 4 seçenekten birini seç",
  startBtn:"▶ Teste başla", dictShortcut:"📖 Sözlüğü aç",
  exportBtn:"⬇ Dışa aktar", importBtn:"⬆ İçe aktar", resetBtn:"↺ Sıfırla",
  autosaveFoot:"İlerleme bu tarayıcıda otomatik olarak kaydedilir. «Dışa aktar», adında tarih ve saat bulunan bir ilerleme dosyası indirir.",
  dictTitle:"📖 Fiil sözlüğü", dictSearchPh:"Ara: mastar, çeviri veya numara…",
  dictTitle_prep:"📖 Edatlı fiiller", dictSearchPh_prep:"Ara: fiil, edat, çeviri veya numara…",
  filterAll:(n)=>"Tümü "+n, filterRange:"Aralıkta",
  hideTransLbl:"Çeviriyi gizle", hidePerfLbl:"Perfekt'i gizle", hidePerfLbl_prep:"Edatı gizle",
  selfCheckFoot:"Kendini sınama modu: «gizle»yi açın ve cevabı görmek için hücreye tıklayın.",
  dheadVerb:"Fiil · Präs · Prät", dheadVerb_prep:"Fiil · örnek",
  dheadPerfekt:"Perfekt", dheadPerfekt_prep:"Edat + hâl", dheadTrans:"Çeviri", dheadFolder:"Klasör",
  transFieldLbl:"Çeviri (Türkçeye)", transFieldPh:"örn. yarıda kesmek",
  perfFieldLbl:"Perfekt (yardımcı fiille)", perfFieldPh:"örn. hat abgebrochen",
  perfFieldLbl_prep:"Edat + hâl", perfFieldPh_prep:"örn. über",
  kasusA:"Akkusativ (A)", kasusD:"Dativ (D)",
  overrideQ:"Bu çeviri kabul edilsin mi?", chipCorrect:"✓ Doğru", chipWrong:"✗ Yanlış",
  checkBtn:"Kontrol et", nextBtn:"İleri →", quitBtn:"Bitir", enterHint:"kontrol / ileri",
  errCardTitle:"Hataların incelenmesi",
  retryWrongBtn:"↻ Bu testin hatalarını tekrarla", againBtn:"🏠 Ana sayfa",
  footerCredit:"kiselkath tarafından hazırlandı",
  presetAll:(n)=>"Tümü 1–"+n,
  rangeWarn:(max)=>`Lütfen geçerli bir aralık girin: 1 ile ${max} arasında sayılar, «başlangıç» ≤ «bitiş».`,
  inDiap:(from,to)=>`${from}–${to} aralığında`,
  savedInfo:(d)=>{ try{ return "💾 İlerleme kaydedildi · "+d.toLocaleString('tr-TR'); }catch(e){ return ""; } },
  saveUnavailable:"⚠ Otomatik kayıt kullanılamıyor — «Dışa aktar»ı kullanın.",
  modes:[
    {k:"all",t:"Tüm aralık",d:"Seçili aralıktaki bütün fiiller"},
    {k:"new",t:"Yeni + öğrenilmedi + tekrar",d:"«Öğrenildi» klasöründe olmayan her şey"},
    {k:"notlearned",t:"Sadece öğrenilmeyenler",d:"Hatalar üzerinde çalışma"},
    {k:"repeated",t:"Sadece tekrar edilenler",d:"«Galiba hatırlıyorum» notunu doğrula"},
    {k:"learned",t:"Sadece öğrenilenler",d:"Aklında kalanı kontrol et"},
  ],
  alertNoRange:"Önce geçerli bir fiil aralığı girin.",
  alertChooseOne:"En az birini seçin: çeviri veya Perfekt.",
  alertChooseOne_prep:"En az birini seçin: çeviri veya edat.",
  alertChooseStatus:"En az bir durum seçin.",
  alertEmptyPool:"Bu klasörde/aralıkta bu test için fiil yok.",
  alertNoWrong:"Bu testte hata yapılmadı.",
  alertPickOption:"Cevap seçeneklerinden birini işaretleyin.",
  alertImported:(n)=>"İçe aktarılan fiil sayısı: "+n,
  alertImportFail:"İlerleme dosyası okunamadı.",
  confirmReset:(n)=>`Bu kursun ilerlemesi sıfırlansın mı (${n} fiilin tümü «yeni» olacak)?`,
  qpos:(i,total,id)=>`Fiil ${i} / ${total} · #${id}`,
  correctYes:"✓ Doğru.", correctNo:"✗ Yanlış.", acceptedYes:"✓ Kabul edildi.",
  valueLbl:"Anlamı:", correctLbl:"Doğru cevap:",
  verdictPerfect:"Mükemmel! 🎉", verdictGreat:"Harika sonuç",
  verdictOk:"Fena değil, ama daha iyisi olabilir", verdictBad:"Biraz daha çalışmak gerek",
  noErrors:"Hata yok — bütün fiiller «Öğrenildi» klasörüne taşındı. 🎉",
  errIntro:(wrong,total)=>`Hatalar: ${total} fiilden <b>${wrong}</b> tanesi. Bu fiiller şimdi 📕 «Öğrenilmedi» klasöründe.`,
  badgeCorrect:"doğru", thVerb:"Fiil", thTrans:"Çeviri", thPerf:"Perfekt", thPerf_prep:"Edat",
  dictAllForms:"tekrar için bütün formlar", dictAllForms_prep:"tekrar için bütün edatlar", dictEmpty:"Hiçbir şey bulunamadı.",
  actLearned:"Öğrenildi", actNotLearned:"Öğrenilmedi", actNew:"Yeni", actRepeated:"Tekrar edildi",
  verbWord:(n)=>"fiil",
  learnFilterTitle:"🗂️ Durum filtresi", learnStartBtn:"▶ Başla",
  learnFinishBtn:"🏁 Bitir / başka set seç",
  learnSetupFoot:"Aralık ve filtre, bu sayfa açık kaldığı sürece hatırlanır.",
  learnTapHint:"Devamı için karta dokun · sonraki kart için kaydır",
  learnTapHint_prep:"Dokun — edat ve anlam · tekrar dokun — örnek · sonraki kart için kaydır",

  /* ---------- «LERNWORTSCHATZ» KURSU ---------- */
  courseWort:"📚 Lernwortschatz B2",
  pageTitle_wort:"DieFliegendeKuh · Lernwortschatz Linie 1 Beruf B2 · Alıştırma, sözlük ve kartlar",
  subtitle_wort:"Lernwortschatz B2 Beruf",
  rangeTitle_wort:"📍 Kelime aralığı",
  chkPerfLbl_wort:"Artikel sorulsun",
  ansModeSub_wort:"çeviri ve «artikel + çoğul» alanı için",
  perfFieldLbl_wort:"Artikel + çoğul",
  perfFieldPh_wort:"örn. -n (umlaut: ¨e veya \"e)",
  hidePerfLbl_wort:"Artikeli gizle",
  dictTitle_wort:"📖 Lernwortschatz B2", dictSearchPh_wort:"Ara: kelime, anlam veya numara…",
  dheadVerb_wort:"Kelime · örnek", dheadPerfekt_wort:"Artikel + çoğul",
  alertChooseOne_wort:"En az birini seç: anlam veya artikel.",
  thPerf_wort:"Artikel + çoğul",
  dictAllForms_wort:"tekrar için tüm kelimeler",
  learnTapHint_wort:"Dokun — artikel ve anlam · tekrar dokun — örnek · sonraki kart için kaydır",
  verbWord_wort:(n)=>"kelime",
  confirmReset_wort:(n)=>`Bu kursun ilerlemesi sıfırlansın mı (${n} kelimenin tümü «yeni» olacak)?`,
});
