"use strict";

/* ---------- ИТАЛЬЯНСКИЙ ---------- */
registerLang("it", { name:"ITA", transField:"transIt", tKeysField:"tKeysIt" }, {
  pageTitle:"DieFliegendeKuh · Unregelmäßige Verben 1–270 · Esercitatore, dizionario e schede",
  pageTitle_prep:"DieFliegendeKuh · Verben mit Präpositionen · Esercitatore, dizionario e schede",
  subtitle:"Unregelmäßige Verben",
  subtitle_prep:"Verben mit Präpositionen",
  courseVerbs:"🔤 Forme dei verbi", coursePrep:"🔗 Verbi con preposizioni",
  navHome:"🎯 Esercitatore", navDict:"📖 Dizionario", navLearn:"🗂️ Schede",
  rangeTitle:"📍 Intervallo di verbi",
  lblFrom:"da", lblTo:"a",
  lblLearned:"📗 Imparato", lblNotLearned:"📕 Non imparato", lblNew:"📘 Nuovo", lblRepeated:"🟡 Ripassato",
  whatTrainTitle:"🎯 Cosa esercitare", whatTrainSub:"nell'intervallo selezionato",
  chkShuffleLbl:"Mescola", chkTransLbl:"Chiedi la traduzione", chkPerfLbl:"Chiedi il Perfekt",
  chkPerfLbl_prep:"Chiedi la preposizione",
  ansModeTitle:"✍️ Come rispondere", ansModeSub:"per il campo Perfekt", ansModeSub_prep:"per il campo «preposizione + caso»",
  ansModeInput:"⌨️ Digitare la risposta", ansModeChoice:"🔘 Scegliere fra 4 opzioni",
  startBtn:"▶ Inizia il test", dictShortcut:"📖 Apri il dizionario",
  exportBtn:"⬇ Esporta", importBtn:"⬆ Importa", resetBtn:"↺ Reimposta",
  autosaveFoot:"Il progresso viene salvato automaticamente in questo browser. «Esporta» scarica un file con data e ora nel nome.",
  dictTitle:"📖 Dizionario dei verbi", dictSearchPh:"Cerca: infinito, traduzione o numero…",
  dictTitle_prep:"📖 Verbi con preposizioni", dictSearchPh_prep:"Cerca: verbo, preposizione, traduzione o numero…",
  filterAll:(n)=>"Tutti i "+n, filterRange:"Nell'intervallo",
  hideTransLbl:"Nascondi traduzione", hidePerfLbl:"Nascondi Perfekt", hidePerfLbl_prep:"Nascondi preposizione",
  selfCheckFoot:"Modalità autoverifica: attiva «nascondi» e clicca su una cella per rivelare la risposta.",
  dheadVerb:"Verbo · Präs · Prät", dheadVerb_prep:"Verbo · esempio",
  dheadPerfekt:"Perfekt", dheadPerfekt_prep:"Preposizione + caso", dheadTrans:"Traduzione", dheadFolder:"Cartella",
  transFieldLbl:"Traduzione (in italiano)", transFieldPh:"es. interrompere",
  perfFieldLbl:"Perfekt (con verbo ausiliare)", perfFieldPh:"es. hat abgebrochen",
  perfFieldLbl_prep:"Preposizione + caso", perfFieldPh_prep:"es. über",
  kasusA:"Akkusativ (A)", kasusD:"Dativ (D)",
  overrideQ:"Considerare corretta la traduzione?", chipCorrect:"✓ Corretto", chipWrong:"✗ Errore",
  checkBtn:"Verifica", nextBtn:"Avanti →", quitBtn:"Termina", enterHint:"verifica / avanti",
  errCardTitle:"Analisi degli errori",
  retryWrongBtn:"↻ Ripeti gli errori di questo test", againBtn:"🏠 Home",
  footerCredit:"Creato da kiselkath",
  presetAll:(n)=>"Tutti 1–"+n,
  rangeWarn:(max)=>`Inserisci un intervallo valido: numeri da 1 a ${max}, «da» ≤ «a».`,
  inDiap:(from,to)=>`nell'intervallo ${from}–${to}`,
  savedInfo:(d)=>{ try{ return "💾 Progresso salvato · "+d.toLocaleString('it-IT'); }catch(e){ return ""; } },
  saveUnavailable:"⚠ Salvataggio automatico non disponibile — usa «Esporta».",
  modes:[
    {k:"all",t:"Tutto l'intervallo",d:"Tutti i verbi dell'intervallo selezionato"},
    {k:"new",t:"Nuovi + non imparati + ripassati",d:"Tutto ciò che non è ancora «Imparato»"},
    {k:"notlearned",t:"Solo non imparati",d:"Lavora sugli errori"},
    {k:"repeated",t:"Solo ripassati",d:"Conferma l'autovalutazione «mi sembra di ricordarlo»"},
    {k:"learned",t:"Solo imparati",d:"Verifica cosa non hai dimenticato"},
  ],
  alertNoRange:"Indica prima un intervallo di verbi valido.",
  alertChooseOne:"Scegli almeno una opzione: traduzione o Perfekt.",
  alertChooseOne_prep:"Scegli almeno una opzione: traduzione o preposizione.",
  alertChooseStatus:"Scegli almeno uno stato.",
  alertEmptyPool:"Non ci sono verbi per questo test in questa cartella/intervallo.",
  alertNoWrong:"Non ci sono stati errori in questo test.",
  alertPickOption:"Scegli una delle opzioni di risposta.",
  alertImported:(n)=>"Verbi importati: "+n,
  alertImportFail:"Impossibile leggere il file di progresso.",
  confirmReset:(n)=>`Reimpostare il progresso di questo corso (tutti i ${n} verbi diventeranno «nuovi»)?`,
  qpos:(i,total,id)=>`Verbo ${i} di ${total} · №${id}`,
  correctYes:"✓ Corretto.", correctNo:"✗ Errore.", acceptedYes:"✓ Accettato.",
  valueLbl:"Significato:", correctLbl:"Risposta corretta:",
  verdictPerfect:"Perfetto! 🎉", verdictGreat:"Ottimo risultato",
  verdictOk:"Non male, ma c'è ancora da lavorare", verdictBad:"Serve altro ripasso",
  noErrors:"Nessun errore — tutti i verbi sono nella cartella «Imparato». 🎉",
  errIntro:(wrong,total)=>`Errori: <b>${wrong}</b> su ${total}. Questi verbi sono ora nella cartella 📕 «Non imparato».`,
  badgeCorrect:"corretto", thVerb:"Verbo", thTrans:"Traduzione", thPerf:"Perfekt", thPerf_prep:"Preposizione",
  dictAllForms:"tutte le forme per il ripasso", dictAllForms_prep:"tutte le preposizioni per il ripasso", dictEmpty:"Nessun risultato.",
  actLearned:"Imparato", actNotLearned:"Non imparato", actNew:"Nuovo", actRepeated:"Ripassato",
  verbWord:(n)=> n===1 ? "verbo" : "verbi",
  learnFilterTitle:"🗂️ Filtro per stato", learnStartBtn:"▶ Inizia",
  learnFinishBtn:"🏁 Termina / scegli un altro set",
  learnSetupFoot:"L'intervallo e il filtro vengono memorizzati finché questa pagina resta aperta.",
  learnTapHint:"Tocca la carta per vedere di più · scorri per la carta successiva",
  learnTapHint_prep:"Tocca — preposizione e significato · ancora — esempio · scorri per la carta successiva",
});
