"use strict";

/* ---------- РУССКИЙ ---------- */
registerLang("ru", { name:"RUS" }, {
  pageTitle:"DieFliegendeKuh · Unregelmäßige Verben 1–270 · Тренажёр, словарь и карточки",
  pageTitle_prep:"DieFliegendeKuh · Verben mit Präpositionen · Тренажёр, словарь и карточки",
  subtitle:"Unregelmäßige Verben",
  subtitle_prep:"Verben mit Präpositionen",
  courseVerbs:"🔤 Формы глаголов", coursePrep:"🔗 Глаголы с предлогами",
  navHome:"🎯 Тренажёр", navDict:"📖 Словарь", navLearn:"🗂️ Карточки",
  rangeTitle:"📍 Диапазон глаголов",
  lblFrom:"от", lblTo:"до",
  lblLearned:"📗 Выучено", lblNotLearned:"📕 Невыучено", lblNew:"📘 Новые", lblRepeated:"🟡 Повторено",
  whatTrainTitle:"🎯 Что тренируем", whatTrainSub:"в выбранном диапазоне",
  chkShuffleLbl:"Перемешать", chkTransLbl:"Спрашивать перевод", chkPerfLbl:"Спрашивать Perfekt",
  chkPerfLbl_prep:"Спрашивать предлог",
  ansModeTitle:"✍️ Как отвечать", ansModeSub:"для перевода и поля Perfekt", ansModeSub_prep:"для перевода и поля «предлог + падеж»",
  ansModeInput:"⌨️ Вводить с клавиатуры", ansModeChoice:"🔘 Выбирать из 4 вариантов",
  startBtn:"▶ Начать тест", dictShortcut:"📖 Открыть словарь",
  exportBtn:"⬇ Экспорт", importBtn:"⬆ Импорт", resetBtn:"↺ Сброс",
  autosaveFoot:"Прогресс автосохраняется в этом браузере. «Экспорт» скачивает файл прогресса с датой и временем в названии.",
  dictTitle:"📖 Словарь глаголов", dictSearchPh:"Поиск: инфинитив, перевод или номер…",
  dictTitle_prep:"📖 Глаголы с предлогами", dictSearchPh_prep:"Поиск: глагол, предлог, перевод или номер…",
  filterAll:(n)=>"Все "+n, filterRange:"В диапазоне",
  hideTransLbl:"Скрыть перевод", hidePerfLbl:"Скрыть Perfekt", hidePerfLbl_prep:"Скрыть предлог",
  selfCheckFoot:"Режим самопроверки: включи «скрыть» и нажимай на ячейку, чтобы открыть ответ.",
  dheadVerb:"Глагол · Präs · Prät", dheadVerb_prep:"Глагол · пример",
  dheadPerfekt:"Perfekt", dheadPerfekt_prep:"Предлог + падеж", dheadTrans:"Перевод", dheadFolder:"Папка",
  transFieldLbl:"Перевод (на русский)", transFieldPh:"напр. прерывать",
  perfFieldLbl:"Perfekt (со вспомог. глаголом)", perfFieldPh:"напр. hat abgebrochen",
  perfFieldLbl_prep:"Предлог + падеж", perfFieldPh_prep:"напр. über",
  kasusA:"Akkusativ (A)", kasusD:"Dativ (D)",
  overrideQ:"Засчитать перевод?", chipCorrect:"✓ Верно", chipWrong:"✗ Ошибка",
  checkBtn:"Проверить", nextBtn:"Дальше →", quitBtn:"Завершить", enterHint:"проверить / дальше",
  errCardTitle:"Разбор ошибок",
  retryWrongBtn:"↻ Повторить ошибки этого теста", againBtn:"🏠 На главную",
  footerCredit:"Собрано kiselkath",
  presetAll:(n)=>"Все 1–"+n,
  rangeWarn:(max)=>`Укажите корректный диапазон: числа от 1 до ${max}, «от» ≤ «до».`,
  inDiap:(from,to)=>`в диапазоне ${from}–${to}`,
  savedInfo:(d)=>{ try{ return "💾 Прогресс сохранён · "+d.toLocaleString('ru-RU'); }catch(e){ return ""; } },
  saveUnavailable:"⚠ Автосохранение недоступно — используйте «Экспорт».",
  modes:[
    {k:"all",t:"Весь диапазон",d:"Все глаголы выбранного интервала"},
    {k:"new",t:"Новые + невыученные + повторённые",d:"Всё, что ещё не в «Выучено»"},
    {k:"notlearned",t:"Только невыученные",d:"Работа над ошибками"},
    {k:"repeated",t:"Только повторённые",d:"Подтвердить самооценку «вроде помню»"},
    {k:"learned",t:"Только выученные",d:"Проверить, что не забылось"},
  ],
  alertNoRange:"Сначала укажите корректный диапазон глаголов.",
  alertChooseOne:"Выберите хотя бы одно: перевод или Perfekt.",
  alertChooseOne_prep:"Выберите хотя бы одно: перевод или предлог.",
  alertChooseStatus:"Выберите хотя бы один статус.",
  alertEmptyPool:"В этой папке/диапазоне нет глаголов для теста.",
  alertNoWrong:"В этом тесте не было ошибок.",
  alertPickOption:"Выберите один из вариантов ответа.",
  alertImported:(n)=>"Импортировано глаголов: "+n,
  alertImportFail:"Не удалось прочитать файл прогресса.",
  confirmReset:(n)=>`Сбросить прогресс этого курса (все ${n} глаголов станут «новыми»)?`,
  qpos:(i,total,id)=>`Глагол ${i} из ${total} · №${id}`,
  correctYes:"✓ Верно.", correctNo:"✗ Ошибка.", acceptedYes:"✓ Засчитано.",
  valueLbl:"Значение:", correctLbl:"Правильно:",
  verdictPerfect:"Идеально! 🎉", verdictGreat:"Отличный результат",
  verdictOk:"Неплохо, но есть над чем поработать", verdictBad:"Нужно ещё повторить",
  noErrors:"Ошибок нет — все глаголы отправлены в папку «Выучено». 🎉",
  errIntro:(wrong,total)=>`Ошибок: <b>${wrong}</b> из ${total}. Эти глаголы теперь в папке 📕 «Невыучено».`,
  badgeCorrect:"верно", thVerb:"Глагол", thTrans:"Перевод", thPerf:"Perfekt", thPerf_prep:"Предлог",
  dictAllForms:"все формы для повторения", dictAllForms_prep:"все предлоги для повторения", dictEmpty:"Ничего не найдено.",
  actLearned:"Выучено", actNotLearned:"Невыучено", actNew:"Новое", actRepeated:"Повторено",
  verbWord:(n)=>{ const f=["глагол","глагола","глаголов"]; const a=n%10,b=n%100; if(a===1&&b!==11)return f[0]; if(a>=2&&a<=4&&(b<10||b>=20))return f[1]; return f[2]; },
  learnFilterTitle:"🗂️ Фильтр по статусу", learnStartBtn:"▶ Начать",
  learnFinishBtn:"🏁 Завершить / выбрать другой набор",
  learnSetupFoot:"Диапазон и фильтр запоминаются, пока открыта эта страница.",
  learnTapHint:"Тап по карточке — рассмотреть · свайп — следующая карточка",
  learnTapHint_prep:"Тап — предлог и перевод · ещё тап — пример · свайп — следующая карточка",

  /* ---------- КУРС «LERNWORTSCHATZ» ---------- */
  courseWort:"📚 Lernwortschatz B2",
  pageTitle_wort:"DieFliegendeKuh · Lernwortschatz Linie 1 Beruf B2 · Тренажёр, словарь и карточки",
  subtitle_wort:"Lernwortschatz B2 Beruf",
  rangeTitle_wort:"📍 Диапазон слов",
  chkPerfLbl_wort:"Спрашивать артикль",
  ansModeSub_wort:"для перевода и поля «артикль + мн. число»",
  perfFieldLbl_wort:"Артикль + множественное число",
  perfFieldPh_wort:"напр. -n (умлаут: ¨e или \"e)",
  hidePerfLbl_wort:"Скрыть артикль",
  dictTitle_wort:"📖 Lernwortschatz B2", dictSearchPh_wort:"Поиск: слово, перевод или номер…",
  dheadVerb_wort:"Слово · пример", dheadPerfekt_wort:"Артикль + мн. ч.",
  alertChooseOne_wort:"Выбери хотя бы одно: перевод или артикль.",
  thPerf_wort:"Артикль + мн. ч.",
  dictAllForms_wort:"все слова для повторения",
  learnTapHint_wort:"Тап — артикль и перевод · ещё тап — пример · свайп — следующая карточка",
  verbWord_wort:(n)=>{ const f=["слово","слова","слов"]; const a=n%10,b=n%100; if(a===1&&b!==11)return f[0]; if(a>=2&&a<=4&&(b<10||b>=20))return f[1]; return f[2]; },
  confirmReset_wort:(n)=>`Сбросить прогресс этого курса (все ${n} слов станут «новыми»)?`,
});
