"use strict";

/* ---------- АНГЛИЙСКИЙ ---------- */
registerLang("en", { name:"ENG" }, {
  pageTitle:"DieFliegendeKuh · Unregelmäßige Verben 1–270 · Trainer, Dictionary & Flashcards",
  pageTitle_prep:"DieFliegendeKuh · Verben mit Präpositionen · Trainer, Dictionary & Flashcards",
  subtitle:"Unregelmäßige Verben",
  subtitle_prep:"Verben mit Präpositionen",
  courseVerbs:"🔤 Verb forms", coursePrep:"🔗 Verbs + prepositions",
  navHome:"🎯 Trainer", navDict:"📖 Dictionary", navLearn:"🗂️ Cards",
  rangeTitle:"📍 Verb range",
  lblFrom:"from", lblTo:"to",
  lblLearned:"📗 Learned", lblNotLearned:"📕 Not learned", lblNew:"📘 New", lblRepeated:"🟡 Repeated",
  whatTrainTitle:"🎯 What to practice", whatTrainSub:"in the selected range",
  chkShuffleLbl:"Shuffle", chkTransLbl:"Ask translation", chkPerfLbl:"Ask Perfekt",
  chkPerfLbl_prep:"Ask preposition",
  ansModeTitle:"✍️ How to answer", ansModeSub:"for the translation and Perfekt fields", ansModeSub_prep:"for the translation and “preposition + case” fields",
  ansModeInput:"⌨️ Type the answer", ansModeChoice:"🔘 Pick one of 4 options",
  startBtn:"▶ Start test", dictShortcut:"📖 Open dictionary",
  exportBtn:"⬇ Export", importBtn:"⬆ Import", resetBtn:"↺ Reset",
  autosaveFoot:"Progress is auto-saved in this browser. “Export” downloads a progress file with the date and time in its name.",
  dictTitle:"📖 Verb dictionary", dictSearchPh:"Search: infinitive, translation or number…",
  dictTitle_prep:"📖 Verbs with prepositions", dictSearchPh_prep:"Search: verb, preposition, translation or number…",
  filterAll:(n)=>"All "+n, filterRange:"In range",
  hideTransLbl:"Hide translation", hidePerfLbl:"Hide Perfekt", hidePerfLbl_prep:"Hide preposition",
  selfCheckFoot:"Self-check mode: turn on “hide” and click a cell to reveal the answer.",
  dheadVerb:"Verb · Präs · Prät", dheadVerb_prep:"Verb · example",
  dheadPerfekt:"Perfekt", dheadPerfekt_prep:"Preposition + case", dheadTrans:"Translation", dheadFolder:"Folder",
  transFieldLbl:"Translation (to English)", transFieldPh:"e.g. interrupt",
  perfFieldLbl:"Perfekt (with auxiliary verb)", perfFieldPh:"e.g. hat abgebrochen",
  perfFieldLbl_prep:"Preposition + case", perfFieldPh_prep:"e.g. über",
  kasusA:"Akkusativ (A)", kasusD:"Dativ (D)",
  overrideQ:"Accept this translation?", chipCorrect:"✓ Correct", chipWrong:"✗ Wrong",
  checkBtn:"Check", nextBtn:"Next →", quitBtn:"Finish", enterHint:"check / next",
  errCardTitle:"Mistake review",
  retryWrongBtn:"↻ Retry this test's mistakes", againBtn:"🏠 Home",
  footerCredit:"Made by kiselkath",
  presetAll:(n)=>"All 1–"+n,
  rangeWarn:(max)=>`Please enter a valid range: numbers from 1 to ${max}, “from” ≤ “to”.`,
  inDiap:(from,to)=>`in range ${from}–${to}`,
  savedInfo:(d)=>{ try{ return "💾 Progress saved · "+d.toLocaleString('en-US'); }catch(e){ return ""; } },
  saveUnavailable:"⚠ Auto-save unavailable — use “Export”.",
  modes:[
    {k:"all",t:"Whole range",d:"All verbs in the selected range"},
    {k:"new",t:"New + not learned + repeated",d:"Everything not yet in “Learned”"},
    {k:"notlearned",t:"Not learned only",d:"Work on mistakes"},
    {k:"repeated",t:"Repeated only",d:"Confirm the “I think I remember” self-check"},
    {k:"learned",t:"Learned only",d:"Check what's retained"},
  ],
  alertNoRange:"Please enter a valid verb range first.",
  alertChooseOne:"Choose at least one: translation or Perfekt.",
  alertChooseOne_prep:"Choose at least one: translation or preposition.",
  alertChooseStatus:"Choose at least one status.",
  alertEmptyPool:"There are no verbs for this test in this folder/range.",
  alertNoWrong:"There were no mistakes in this test.",
  alertPickOption:"Pick one of the answer options.",
  alertImported:(n)=>"Verbs imported: "+n,
  alertImportFail:"Could not read the progress file.",
  confirmReset:(n)=>`Reset this course's progress (all ${n} verbs will become “new”)?`,
  qpos:(i,total,id)=>`Verb ${i} of ${total} · #${id}`,
  correctYes:"✓ Correct.", correctNo:"✗ Wrong.", acceptedYes:"✓ Accepted.",
  valueLbl:"Meaning:", correctLbl:"Correct answer:",
  verdictPerfect:"Perfect! 🎉", verdictGreat:"Great result",
  verdictOk:"Not bad, but there's room to improve", verdictBad:"Needs more practice",
  noErrors:"No mistakes — all verbs moved to the “Learned” folder. 🎉",
  errIntro:(wrong,total)=>`Mistakes: <b>${wrong}</b> of ${total}. These verbs are now in the 📕 “Not learned” folder.`,
  badgeCorrect:"correct", thVerb:"Verb", thTrans:"Translation", thPerf:"Perfekt", thPerf_prep:"Preposition",
  dictAllForms:"all forms for review", dictAllForms_prep:"all prepositions for review", dictEmpty:"Nothing found.",
  actLearned:"Learned", actNotLearned:"Not learned", actNew:"New", actRepeated:"Repeated",
  verbWord:(n)=> n===1 ? "verb" : "verbs",
  learnFilterTitle:"🗂️ Status filter", learnStartBtn:"▶ Start",
  learnFinishBtn:"🏁 Finish / choose another set",
  learnSetupFoot:"The range and filter are remembered while this page stays open.",
  learnTapHint:"Tap the card to reveal more · swipe for the next card",
  learnTapHint_prep:"Tap — preposition and meaning · tap again — example · swipe for the next card",

  /* ---------- LERNWORTSCHATZ COURSE ---------- */
  courseWort:"📚 Lernwortschatz B2",
  pageTitle_wort:"DieFliegendeKuh · Lernwortschatz Linie 1 Beruf B2 · Trainer, Dictionary & Flashcards",
  subtitle_wort:"Lernwortschatz B2 Beruf",
  rangeTitle_wort:"📍 Word range",
  chkPerfLbl_wort:"Ask article",
  ansModeSub_wort:"for the translation and “article + plural” fields",
  perfFieldLbl_wort:"Article + plural",
  perfFieldPh_wort:"e.g. -n (umlaut: ¨e or \"e)",
  hidePerfLbl_wort:"Hide article",
  dictTitle_wort:"📖 Lernwortschatz B2", dictSearchPh_wort:"Search: word, translation or number…",
  dheadVerb_wort:"Word · example", dheadPerfekt_wort:"Article + plural",
  alertChooseOne_wort:"Choose at least one: translation or article.",
  thPerf_wort:"Article + plural",
  dictAllForms_wort:"all words for review",
  learnTapHint_wort:"Tap — article and meaning · tap again — example · swipe for the next card",
  verbWord_wort:(n)=> n===1 ? "word" : "words",
  confirmReset_wort:(n)=>`Reset this course's progress (all ${n} words will become “new”)?`,
});
